name: palomansion
description: A measurement of sound level app.
publish_to: 'none'
version: 0.1.1+4
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.16.0
  # Firebase
  firebase_core: ^1.21.0
  # UI
  syncfusion_flutter_charts: ^20.3.59
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"
flutter_native_splash:
  color: "#000000"
  image: "assets/images/ic_launcher.png"
