name: Chore

on:
  push:
    branches-ignore:
      - 'main'

env:
  FLUTTER_VERSION: '3.0.5'
  WORKING_FLUTTER_DIRECTORY: 'flutter'

jobs:
  flutter_formatter:
    name: Flutter formatter
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      - working-directory: ${{ env.WORKING_FLUTTER_DIRECTORY }}
        run: flutter pub get
      - working-directory: ${{ env.WORKING_FLUTTER_DIRECTORY }}
        run: flutter format ./lib/ ./test/
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[style] Flutter Auto Format'
